export const GET_CATALOGS = "GET_CATALOGS";
export const GET_CATALOGS_RECENTLY_ADDED = "GET_CATALOGS_RECENTLY_ADDED";

export const GET_MARKETS = "GET_MARKETS";
export const SELECT_MARKET = "SELECT_MARKET";

export const SWITCH_PAGE = "SWITCH_PAGE";

export const SET_MESSAGE = "SET_MESSAGE";

export const SET_LANG = "SET_LANG";
export const SET_THEME = "SET_THEME";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
