export const GET_CATALOGS_BY_MARKET = "GET_CATALOGS_BY_MARKET";
export const GET_CATALOGS_RECENTLY_ADDED = "GET_CATALOGS_RECENTLY_ADDED";

export const GET_MARKETS = "GET_MARKETS";
export const SELECT_MARKET = "SELECT_MARKET";

export const SWITCH_PAGE = "SWITCH_PAGE";
